# scripts/data_motors_part3.py
MOTORS_PART3 = [
  {
    "id": "ID-MOT101-REF-REF3KW2950-PRM21-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT101-REF-REF3KW2950-PRM21-ZONE-PRESSE-MATRICE",
    "code": "mot 101",
    "ref": "REF-3KW-2950",
    "libelle": "Moteur Asynchrone 3KW 4CV 2950 tr/min",
    "id_template": "TPL-MOT-ASYNC-101",
    "id_templates": "TPL-MOT-ASYNC-101",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-21",
    "emplacement": "PRM-21",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT102-REF-REF22KW2950-PRM22-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT102-REF-REF22KW2950-PRM22-ZONE-PRESSE-MATRICE",
    "code": "mot 102",
    "ref": "REF-22KW-2950",
    "libelle": "Moteur Asynchrone 2,2 KW 3 CV 2950 tr/min",
    "id_template": "TPL-MOT-ASYNC-102",
    "id_templates": "TPL-MOT-ASYNC-102",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-22",
    "emplacement": "PRM-22",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT103-REF-REF3KW3KW2860-PRM23-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT103-REF-REF3KW3KW2860-PRM23-ZONE-PRESSE-MATRICE",
    "code": "mot 103",
    "ref": "REF-3KW3KW-2860",
    "libelle": "Moteur Asynchrone 3KW                 3KW              3KW 4 CV              4CV               4CV 2860               2860            2860 tr/min",
    "id_template": "TPL-MOT-ASYNC-103",
    "id_templates": "TPL-MOT-ASYNC-103",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-23",
    "emplacement": "PRM-23",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT104-REF-REF11KW940-PRM24-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT104-REF-REF11KW940-PRM24-ZONE-PRESSE-MATRICE",
    "code": "mot 104",
    "ref": "REF-11KW-940",
    "libelle": "Moteur Asynchrone 1,1KW 1,5CV 940 tr/min",
    "id_template": "TPL-MOT-ASYNC-104",
    "id_templates": "TPL-MOT-ASYNC-104",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-24",
    "emplacement": "PRM-24",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT105-REF-REF04KW1380-PRM25-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT105-REF-REF04KW1380-PRM25-ZONE-PRESSE-MATRICE",
    "code": "mot 105",
    "ref": "REF-04KW-1380",
    "libelle": "Moteur Asynchrone 0,4KW 0,5CV 1380 tr/min",
    "id_template": "TPL-MOT-ASYNC-105",
    "id_templates": "TPL-MOT-ASYNC-105",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-25",
    "emplacement": "PRM-25",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT106-REF-REF15940-PRM-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT106-REF-REF15940-PRM-ZONE-PRESSE-MATRICE",
    "code": "mot 106",
    "ref": "REF-15-940",
    "libelle": "Moteur Asynchrone 1.5 2 940 tr/min",
    "id_template": "TPL-MOT-ASYNC-106",
    "id_templates": "TPL-MOT-ASYNC-106",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-",
    "emplacement": "PRM-",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT107-REF-REF1651456-POA08-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT107-REF-REF1651456-POA08-ZONE-PRESSE-POLYESTER",
    "code": "mot 107",
    "ref": "REF-165-1456",
    "libelle": "Moteur Asynchrone 16.5 20CV 2CV 1456 1420 tr/min",
    "id_template": "TPL-MOT-ASYNC-107",
    "id_templates": "TPL-MOT-ASYNC-107",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-08",
    "emplacement": "POA-08",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT108-REF-REF803000-POA08-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT108-REF-REF803000-POA08-ZONE-PRESSE-POLYESTER",
    "code": "mot 108",
    "ref": "REF-80-3000",
    "libelle": "Moteur Asynchrone 80 * 3000 tr/min",
    "id_template": "TPL-MOT-ASYNC-108",
    "id_templates": "TPL-MOT-ASYNC-108",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-08",
    "emplacement": "POA-08",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT109-REF-REF0131400-PCE-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "id_entrepot": "ID-MOT109-REF-REF0131400-PCE-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "code": "mot 109",
    "ref": "REF-013-1400",
    "libelle": "Moteur Asynchrone 0.13 0.17 1400 tr/min",
    "id_template": "TPL-MOT-ASYNC-109",
    "id_templates": "TPL-MOT-ASYNC-109",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PCE-",
    "emplacement": "PCE-",
    "zone": "Préparation Corniche et Emballage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT110-REF-REF2155NA-POA08-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT110-REF-REF2155NA-POA08-ZONE-PRESSE-POLYESTER",
    "code": "mot 110",
    "ref": "REF-2155-NA",
    "libelle": "Moteur Asynchrone 215.5 TOTAL AMP tr/min",
    "id_template": "TPL-MOT-ASYNC-110",
    "id_templates": "TPL-MOT-ASYNC-110",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-08",
    "emplacement": "POA-08",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT111-REF-REF441430-FRL-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT111-REF-REF441430-FRL-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 111",
    "ref": "REF-44-1430",
    "libelle": "Moteur Asynchrone 4.4 3 CV 3 CV 1430 1430 tr/min",
    "id_template": "TPL-MOT-ASYNC-111",
    "id_templates": "TPL-MOT-ASYNC-111",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-",
    "emplacement": "FRL-",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT112-REF-REF213000-FRL-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT112-REF-REF213000-FRL-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 112",
    "ref": "REF-21-3000",
    "libelle": "Moteur Asynchrone 2.1 3CV 3000 tr/min",
    "id_template": "TPL-MOT-ASYNC-112",
    "id_templates": "TPL-MOT-ASYNC-112",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-",
    "emplacement": "FRL-",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT113-REF-REF074900-FRL-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT113-REF-REF074900-FRL-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 113",
    "ref": "REF-074-900",
    "libelle": "Moteur Asynchrone 0.74 1CV 900 tr/min",
    "id_template": "TPL-MOT-ASYNC-113",
    "id_templates": "TPL-MOT-ASYNC-113",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-",
    "emplacement": "FRL-",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT114-REF-REF10NA-FRL-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT114-REF-REF10NA-FRL-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 114",
    "ref": "REF-10-NA",
    "libelle": "Moteur Asynchrone 10 * * tr/min",
    "id_template": "TPL-MOT-ASYNC-114",
    "id_templates": "TPL-MOT-ASYNC-114",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-",
    "emplacement": "FRL-",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT115-REF-REF451475-POA-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT115-REF-REF451475-POA-ZONE-PRESSE-POLYESTER",
    "code": "mot 115",
    "ref": "REF-45-1475",
    "libelle": "Moteur Asynchrone 45 1475 tr/min",
    "id_template": "TPL-MOT-ASYNC-115",
    "id_templates": "TPL-MOT-ASYNC-115",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-",
    "emplacement": "POA-",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT116-REF-REF751475-POA-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT116-REF-REF751475-POA-ZONE-PRESSE-POLYESTER",
    "code": "mot 116",
    "ref": "REF-75-1475",
    "libelle": "Moteur Asynchrone 75 1475 tr/min",
    "id_template": "TPL-MOT-ASYNC-116",
    "id_templates": "TPL-MOT-ASYNC-116",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-",
    "emplacement": "POA-",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT117-REF-REF151450-POA-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT117-REF-REF151450-POA-ZONE-PRESSE-POLYESTER",
    "code": "mot 117",
    "ref": "REF-15-1450",
    "libelle": "Moteur Asynchrone 15 1450 tr/min",
    "id_template": "TPL-MOT-ASYNC-117",
    "id_templates": "TPL-MOT-ASYNC-117",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-",
    "emplacement": "POA-",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT118-REF-REF30151470-POA-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT118-REF-REF30151470-POA-ZONE-PRESSE-POLYESTER",
    "code": "mot 118",
    "ref": "REF-3015-1470",
    "libelle": "Moteur Asynchrone 30 1,5 1470 tr/min",
    "id_template": "TPL-MOT-ASYNC-118",
    "id_templates": "TPL-MOT-ASYNC-118",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-",
    "emplacement": "POA-",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT119-REF-REF49001-PRH-ZONE-PRESSE-HENICKE",
    "id_entrepot": "ID-MOT119-REF-REF49001-PRH-ZONE-PRESSE-HENICKE",
    "code": "mot 119",
    "ref": "REF-4-9001",
    "libelle": "Moteur Asynchrone 4 8,/12 900 1400 tr/min",
    "id_template": "TPL-MOT-ASYNC-119",
    "id_templates": "TPL-MOT-ASYNC-119",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRH-",
    "emplacement": "PRH-",
    "zone": "Presse Hénické",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT120-REF-REF96NA-PRM-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT120-REF-REF96NA-PRM-ZONE-PRESSE-MATRICE",
    "code": "mot 120",
    "ref": "REF-96-NA",
    "libelle": "Moteur Asynchrone 9,/,6 tr/min",
    "id_template": "TPL-MOT-ASYNC-120",
    "id_templates": "TPL-MOT-ASYNC-120",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-",
    "emplacement": "PRM-",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT121-REF-REF111450-PRM-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT121-REF-REF111450-PRM-ZONE-PRESSE-MATRICE",
    "code": "mot 121",
    "ref": "REF-11-1450",
    "libelle": "Moteur Asynchrone 11 15 1450 tr/min",
    "id_template": "TPL-MOT-ASYNC-121",
    "id_templates": "TPL-MOT-ASYNC-121",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-",
    "emplacement": "PRM-",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT122-REF-REF10A111NA-DET01-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT122-REF-REF10A111NA-DET01-ZONE-DETOURAGE",
    "code": "mot 122",
    "ref": "REF-10A111-NA",
    "libelle": "Moteur Asynchrone 10A-11,1A/1,1A   tr/min",
    "id_template": "TPL-MOT-ASYNC-001",
    "id_templates": "TPL-MOT-ASYNC-001",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-01",
    "emplacement": "DET-01",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT123-REF-REF40KWNA-DET02-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT123-REF-REF40KWNA-DET02-ZONE-DETOURAGE",
    "code": "mot 123",
    "ref": "REF-40KW-NA",
    "libelle": "Moteur Asynchrone 4,0KW   tr/min",
    "id_template": "TPL-MOT-ASYNC-002",
    "id_templates": "TPL-MOT-ASYNC-002",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-02",
    "emplacement": "DET-02",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT124-REF-REF75KW05NA-DET03-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT124-REF-REF75KW05NA-DET03-ZONE-DETOURAGE",
    "code": "mot 124",
    "ref": "REF-75KW05-NA",
    "libelle": "Moteur Asynchrone 7,5 KW/0,55KW   tr/min",
    "id_template": "TPL-MOT-ASYNC-003",
    "id_templates": "TPL-MOT-ASYNC-003",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-03",
    "emplacement": "DET-03",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT125-REF-REF3ANA-DET04-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT125-REF-REF3ANA-DET04-ZONE-DETOURAGE",
    "code": "mot 125",
    "ref": "REF-3A-NA",
    "libelle": "Moteur Asynchrone 3A   tr/min",
    "id_template": "TPL-MOT-ASYNC-004",
    "id_templates": "TPL-MOT-ASYNC-004",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-04",
    "emplacement": "DET-04",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT126-REF-REF22KWNA-DET05-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT126-REF-REF22KWNA-DET05-ZONE-DETOURAGE",
    "code": "mot 126",
    "ref": "REF-22KW-NA",
    "libelle": "Moteur Asynchrone 2,2KW   tr/min",
    "id_template": "TPL-MOT-ASYNC-005",
    "id_templates": "TPL-MOT-ASYNC-005",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-05",
    "emplacement": "DET-05",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT127-REF-REF55KWNA-DET06-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT127-REF-REF55KWNA-DET06-ZONE-DETOURAGE",
    "code": "mot 127",
    "ref": "REF-55KW-NA",
    "libelle": "Moteur Asynchrone 5,5KW   tr/min",
    "id_template": "TPL-MOT-ASYNC-006",
    "id_templates": "TPL-MOT-ASYNC-006",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-06",
    "emplacement": "DET-06",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT128-REF-REF27ANA-DET07-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT128-REF-REF27ANA-DET07-ZONE-DETOURAGE",
    "code": "mot 128",
    "ref": "REF-27A-NA",
    "libelle": "Moteur Asynchrone 2,7A   tr/min",
    "id_template": "TPL-MOT-ASYNC-007",
    "id_templates": "TPL-MOT-ASYNC-007",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-07",
    "emplacement": "DET-07",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT129-REF-REF716ANA-DET08-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT129-REF-REF716ANA-DET08-ZONE-DETOURAGE",
    "code": "mot 129",
    "ref": "REF-716A-NA",
    "libelle": "Moteur Asynchrone 7,16A   tr/min",
    "id_template": "TPL-MOT-ASYNC-008",
    "id_templates": "TPL-MOT-ASYNC-008",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-08",
    "emplacement": "DET-08",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT130-REF-REF45KWNA-DET09-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT130-REF-REF45KWNA-DET09-ZONE-DETOURAGE",
    "code": "mot 130",
    "ref": "REF-45KW-NA",
    "libelle": "Moteur Asynchrone 4,5KW   tr/min",
    "id_template": "TPL-MOT-ASYNC-009",
    "id_templates": "TPL-MOT-ASYNC-009",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-09",
    "emplacement": "DET-09",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT131-REF-REF15KW1400-PCE01-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "id_entrepot": "ID-MOT131-REF-REF15KW1400-PCE01-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "code": "mot 131",
    "ref": "REF-15KW-1400",
    "libelle": "Moteur Asynchrone 1,5KW 2CV 1400 tr/min",
    "id_template": "TPL-MOT-ASYNC-010",
    "id_templates": "TPL-MOT-ASYNC-010",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PCE-01",
    "emplacement": "PCE-01",
    "zone": "Préparation Corniche et Emballage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT132-REF-REF75KW920-FRL01-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT132-REF-REF75KW920-FRL01-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 132",
    "ref": "REF-75KW-920",
    "libelle": "Moteur Asynchrone 7,5KW 10CV 920 tr/min",
    "id_template": "TPL-MOT-ASYNC-011",
    "id_templates": "TPL-MOT-ASYNC-011",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-01",
    "emplacement": "FRL-01",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT133-REF-REF9KW1430-FRL02-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT133-REF-REF9KW1430-FRL02-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 133",
    "ref": "REF-9KW-1430",
    "libelle": "Moteur Asynchrone 9KW 12,5CV 1430 tr/min",
    "id_template": "TPL-MOT-ASYNC-012",
    "id_templates": "TPL-MOT-ASYNC-012",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-02",
    "emplacement": "FRL-02",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT134-REF-REF22KW1500-FRL03-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT134-REF-REF22KW1500-FRL03-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 134",
    "ref": "REF-22KW-1500",
    "libelle": "Moteur Asynchrone 2,2KW 3CV 1500 tr/min",
    "id_template": "TPL-MOT-ASYNC-013",
    "id_templates": "TPL-MOT-ASYNC-013",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-03",
    "emplacement": "FRL-03",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT135-REF-REF075KW1410-FRL04-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT135-REF-REF075KW1410-FRL04-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 135",
    "ref": "REF-075KW-1410",
    "libelle": "Moteur Asynchrone 0,75KW 1CV 1410 tr/min",
    "id_template": "TPL-MOT-ASYNC-014",
    "id_templates": "TPL-MOT-ASYNC-014",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-04",
    "emplacement": "FRL-04",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT136-REF-REF075KW1350-FRL05-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT136-REF-REF075KW1350-FRL05-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 136",
    "ref": "REF-075KW-1350",
    "libelle": "Moteur Asynchrone 0,75KW 1CV 1350 tr/min",
    "id_template": "TPL-MOT-ASYNC-015",
    "id_templates": "TPL-MOT-ASYNC-015",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-05",
    "emplacement": "FRL-05",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT137-REF-REF3KW1400-FRL06-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT137-REF-REF3KW1400-FRL06-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 137",
    "ref": "REF-3KW-1400",
    "libelle": "Moteur Asynchrone 3KW 4CV 1400 tr/min",
    "id_template": "TPL-MOT-ASYNC-016",
    "id_templates": "TPL-MOT-ASYNC-016",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-06",
    "emplacement": "FRL-06",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT138-REF-REF3KW1430-FRL07-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT138-REF-REF3KW1430-FRL07-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 138",
    "ref": "REF-3KW-1430",
    "libelle": "Moteur Asynchrone 3KW 4CV 1430 tr/min",
    "id_template": "TPL-MOT-ASYNC-017",
    "id_templates": "TPL-MOT-ASYNC-017",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-07",
    "emplacement": "FRL-07",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT139-REF-REF11KW1460-FRL08-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT139-REF-REF11KW1460-FRL08-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 139",
    "ref": "REF-11KW-1460",
    "libelle": "Moteur Asynchrone 11KW 15CV 1460 tr/min",
    "id_template": "TPL-MOT-ASYNC-018",
    "id_templates": "TPL-MOT-ASYNC-018",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-08",
    "emplacement": "FRL-08",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT140-REF-REF4KW1425-FRL09-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT140-REF-REF4KW1425-FRL09-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 140",
    "ref": "REF-4KW-1425",
    "libelle": "Moteur Asynchrone 4 KW 5,5CV 1425 tr/min",
    "id_template": "TPL-MOT-ASYNC-019",
    "id_templates": "TPL-MOT-ASYNC-019",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-09",
    "emplacement": "FRL-09",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT141-REF-REF21KW880-FRL10-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT141-REF-REF21KW880-FRL10-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 141",
    "ref": "REF-21KW-880",
    "libelle": "Moteur Asynchrone 2,1 KW 2,8CV 880 tr/min",
    "id_template": "TPL-MOT-ASYNC-020",
    "id_templates": "TPL-MOT-ASYNC-020",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-10",
    "emplacement": "FRL-10",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT142-REF-REF11KW1460-FRL11-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT142-REF-REF11KW1460-FRL11-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 142",
    "ref": "REF-11KW-1460",
    "libelle": "Moteur Asynchrone 11 KW 14CV 1460 tr/min",
    "id_template": "TPL-MOT-ASYNC-021",
    "id_templates": "TPL-MOT-ASYNC-021",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-11",
    "emplacement": "FRL-11",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT143-REF-REF75KW1435-FRL12-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT143-REF-REF75KW1435-FRL12-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 143",
    "ref": "REF-75KW-1435",
    "libelle": "Moteur Asynchrone 7,5 KW 10CV 1435 tr/min",
    "id_template": "TPL-MOT-ASYNC-022",
    "id_templates": "TPL-MOT-ASYNC-022",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-12",
    "emplacement": "FRL-12",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT144-REF-REF22KW1460-FRL13-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT144-REF-REF22KW1460-FRL13-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 144",
    "ref": "REF-22KW-1460",
    "libelle": "Moteur Asynchrone 2,2KW 3CV 1460 tr/min",
    "id_template": "TPL-MOT-ASYNC-023",
    "id_templates": "TPL-MOT-ASYNC-023",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-13",
    "emplacement": "FRL-13",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT145-REF-REF75KW1460-FRL14-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT145-REF-REF75KW1460-FRL14-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 145",
    "ref": "REF-75KW-1460",
    "libelle": "Moteur Asynchrone 7,5KW 10CV 1460 tr/min",
    "id_template": "TPL-MOT-ASYNC-024",
    "id_templates": "TPL-MOT-ASYNC-024",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-14",
    "emplacement": "FRL-14",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT146-REF-REF75KW2910-FRL15-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT146-REF-REF75KW2910-FRL15-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 146",
    "ref": "REF-75KW-2910",
    "libelle": "Moteur Asynchrone 7,5 KW 10CV 2910 tr/min",
    "id_template": "TPL-MOT-ASYNC-025",
    "id_templates": "TPL-MOT-ASYNC-025",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-15",
    "emplacement": "FRL-15",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT147-REF-REF44KW1430-FRL16-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT147-REF-REF44KW1430-FRL16-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 147",
    "ref": "REF-44KW-1430",
    "libelle": "Moteur Asynchrone 4,4KW 6CV 1430 tr/min",
    "id_template": "TPL-MOT-ASYNC-026",
    "id_templates": "TPL-MOT-ASYNC-026",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-16",
    "emplacement": "FRL-16",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT148-REF-REF11KW960-FRL17-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT148-REF-REF11KW960-FRL17-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 148",
    "ref": "REF-11KW-960",
    "libelle": "Moteur Asynchrone 11KW 15CV 960 tr/min",
    "id_template": "TPL-MOT-ASYNC-027",
    "id_templates": "TPL-MOT-ASYNC-027",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-17",
    "emplacement": "FRL-17",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT149-REF-REF147KW1337-FRL18-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT149-REF-REF147KW1337-FRL18-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 149",
    "ref": "REF-147KW-1337",
    "libelle": "Moteur Asynchrone 14,7kw 20CV 1337 tr/min",
    "id_template": "TPL-MOT-ASYNC-028",
    "id_templates": "TPL-MOT-ASYNC-028",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-18",
    "emplacement": "FRL-18",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT150-REF-REF22KW1430-FRL19-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT150-REF-REF22KW1430-FRL19-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 150",
    "ref": "REF-22KW-1430",
    "libelle": "Moteur Asynchrone 2,2KW 3 CV 1430 tr/min",
    "id_template": "TPL-MOT-ASYNC-029",
    "id_templates": "TPL-MOT-ASYNC-029",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-19",
    "emplacement": "FRL-19",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  }
]
