# scripts/data_motors_part2.py
MOTORS_PART2 = [
  {
    "id": "ID-MOT51-REF-REF57KWNA-POA18-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT51-REF-REF57KWNA-POA18-ZONE-PRESSE-POLYESTER",
    "code": "mot 51",
    "ref": "REF-57KW-NA",
    "libelle": "Moteur Asynchrone 5,7KW * * tr/min",
    "id_template": "TPL-MOT-ASYNC-051",
    "id_templates": "TPL-MOT-ASYNC-051",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-18",
    "emplacement": "POA-18",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT52-REF-REF74KWNA-POA19-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT52-REF-REF74KWNA-POA19-ZONE-PRESSE-POLYESTER",
    "code": "mot 52",
    "ref": "REF-74KW-NA",
    "libelle": "Moteur Asynchrone 7,4 KW * * tr/min",
    "id_template": "TPL-MOT-ASYNC-052",
    "id_templates": "TPL-MOT-ASYNC-052",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-19",
    "emplacement": "POA-19",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT53-REF-REF74KWNA-POA20-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT53-REF-REF74KWNA-POA20-ZONE-PRESSE-POLYESTER",
    "code": "mot 53",
    "ref": "REF-74KW-NA",
    "libelle": "Moteur Asynchrone 7,4KW * * tr/min",
    "id_template": "TPL-MOT-ASYNC-053",
    "id_templates": "TPL-MOT-ASYNC-053",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-20",
    "emplacement": "POA-20",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT54-REF-REF55KWNA-POA21-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT54-REF-REF55KWNA-POA21-ZONE-PRESSE-POLYESTER",
    "code": "mot 54",
    "ref": "REF-55KW-NA",
    "libelle": "Moteur Asynchrone 5,5KW * * tr/min",
    "id_template": "TPL-MOT-ASYNC-054",
    "id_templates": "TPL-MOT-ASYNC-054",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-21",
    "emplacement": "POA-21",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT55-REF-REF5KWNA-POA22-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT55-REF-REF5KWNA-POA22-ZONE-PRESSE-POLYESTER",
    "code": "mot 55",
    "ref": "REF-5KW-NA",
    "libelle": "Moteur Asynchrone 5KW * * tr/min",
    "id_template": "TPL-MOT-ASYNC-055",
    "id_templates": "TPL-MOT-ASYNC-055",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-22",
    "emplacement": "POA-22",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT56-REF-REF7KWNA-POA23-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT56-REF-REF7KWNA-POA23-ZONE-PRESSE-POLYESTER",
    "code": "mot 56",
    "ref": "REF-7KW-NA",
    "libelle": "Moteur Asynchrone 7KW * * tr/min",
    "id_template": "TPL-MOT-ASYNC-056",
    "id_templates": "TPL-MOT-ASYNC-056",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-23",
    "emplacement": "POA-23",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT57-REF-REF65KWNA-POA24-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT57-REF-REF65KWNA-POA24-ZONE-PRESSE-POLYESTER",
    "code": "mot 57",
    "ref": "REF-65KW-NA",
    "libelle": "Moteur Asynchrone 6,5KW * * tr/min",
    "id_template": "TPL-MOT-ASYNC-057",
    "id_templates": "TPL-MOT-ASYNC-057",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-24",
    "emplacement": "POA-24",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT58-REF-REF185KW1420-POA25-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT58-REF-REF185KW1420-POA25-ZONE-PRESSE-POLYESTER",
    "code": "mot 58",
    "ref": "REF-185KW-1420",
    "libelle": "Moteur Asynchrone 18,5kw 25CV 1420 tr/min",
    "id_template": "TPL-MOT-ASYNC-058",
    "id_templates": "TPL-MOT-ASYNC-058",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-25",
    "emplacement": "POA-25",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT59-REF-REF185KW1450-POA26-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT59-REF-REF185KW1450-POA26-ZONE-PRESSE-POLYESTER",
    "code": "mot 59",
    "ref": "REF-185KW-1450",
    "libelle": "Moteur Asynchrone 18,5kw 25CV 1450 tr/min",
    "id_template": "TPL-MOT-ASYNC-059",
    "id_templates": "TPL-MOT-ASYNC-059",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-26",
    "emplacement": "POA-26",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT60-REF-REF185KW970-POA27-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT60-REF-REF185KW970-POA27-ZONE-PRESSE-POLYESTER",
    "code": "mot 60",
    "ref": "REF-185KW-970",
    "libelle": "Moteur Asynchrone 18,5kw 25CV 970 tr/min",
    "id_template": "TPL-MOT-ASYNC-060",
    "id_templates": "TPL-MOT-ASYNC-060",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-27",
    "emplacement": "POA-27",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT61-REF-REF11KW910-POA28-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT61-REF-REF11KW910-POA28-ZONE-PRESSE-POLYESTER",
    "code": "mot 61",
    "ref": "REF-11KW-910",
    "libelle": "Moteur Asynchrone 1,1 KW 1,5 CV 910 tr/min",
    "id_template": "TPL-MOT-ASYNC-061",
    "id_templates": "TPL-MOT-ASYNC-061",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-28",
    "emplacement": "POA-28",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT62-REF-REF65KW1400-POA29-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT62-REF-REF65KW1400-POA29-ZONE-PRESSE-POLYESTER",
    "code": "mot 62",
    "ref": "REF-65KW-1400",
    "libelle": "Moteur Asynchrone 6,5KW 9 CV 1400 tr/min",
    "id_template": "TPL-MOT-ASYNC-062",
    "id_templates": "TPL-MOT-ASYNC-062",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-29",
    "emplacement": "POA-29",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT63-REF-REF9511KW1460-POA30-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT63-REF-REF9511KW1460-POA30-ZONE-PRESSE-POLYESTER",
    "code": "mot 63",
    "ref": "REF-9511KW-1460",
    "libelle": "Moteur Asynchrone 9,5/11KW 13CV 1460-2930 tr/min",
    "id_template": "TPL-MOT-ASYNC-063",
    "id_templates": "TPL-MOT-ASYNC-063",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-30",
    "emplacement": "POA-30",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT64-REF-REF15KW1450-POA31-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT64-REF-REF15KW1450-POA31-ZONE-PRESSE-POLYESTER",
    "code": "mot 64",
    "ref": "REF-15KW-1450",
    "libelle": "Moteur Asynchrone 15KW 20CV 1450 tr/min",
    "id_template": "TPL-MOT-ASYNC-064",
    "id_templates": "TPL-MOT-ASYNC-064",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-31",
    "emplacement": "POA-31",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT65-REF-REF9511KW1460-POA32-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT65-REF-REF9511KW1460-POA32-ZONE-PRESSE-POLYESTER",
    "code": "mot 65",
    "ref": "REF-9511KW-1460",
    "libelle": "Moteur Asynchrone 9,5/11KW 13 CV 1460-2930 tr/min",
    "id_template": "TPL-MOT-ASYNC-065",
    "id_templates": "TPL-MOT-ASYNC-065",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-32",
    "emplacement": "POA-32",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT66-REF-REF11KW2920-POA33-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT66-REF-REF11KW2920-POA33-ZONE-PRESSE-POLYESTER",
    "code": "mot 66",
    "ref": "REF-11KW-2920",
    "libelle": "Moteur Asynchrone 11KW 15CV 2920 tr/min",
    "id_template": "TPL-MOT-ASYNC-066",
    "id_templates": "TPL-MOT-ASYNC-066",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-33",
    "emplacement": "POA-33",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT67-REF-REF11KW2918-POA34-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT67-REF-REF11KW2918-POA34-ZONE-PRESSE-POLYESTER",
    "code": "mot 67",
    "ref": "REF-11KW-2918",
    "libelle": "Moteur Asynchrone 11KW 15CV 2918 tr/min",
    "id_template": "TPL-MOT-ASYNC-067",
    "id_templates": "TPL-MOT-ASYNC-067",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-34",
    "emplacement": "POA-34",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT68-REF-REF75KW2910-POA35-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT68-REF-REF75KW2910-POA35-ZONE-PRESSE-POLYESTER",
    "code": "mot 68",
    "ref": "REF-75KW-2910",
    "libelle": "Moteur Asynchrone 7,5KW 10HP 2910 tr/min",
    "id_template": "TPL-MOT-ASYNC-068",
    "id_templates": "TPL-MOT-ASYNC-068",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-35",
    "emplacement": "POA-35",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT69-REF-REF75KW2910-POA36-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT69-REF-REF75KW2910-POA36-ZONE-PRESSE-POLYESTER",
    "code": "mot 69",
    "ref": "REF-75KW-2910",
    "libelle": "Moteur Asynchrone 7,5KW  10CV 2910 tr/min",
    "id_template": "TPL-MOT-ASYNC-069",
    "id_templates": "TPL-MOT-ASYNC-069",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-36",
    "emplacement": "POA-36",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT70-REF-REF7555KW2840-POA37-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT70-REF-REF7555KW2840-POA37-ZONE-PRESSE-POLYESTER",
    "code": "mot 70",
    "ref": "REF-7555KW-2840",
    "libelle": "Moteur Asynchrone 7,5-5,5KW 10CV 2840 tr/min",
    "id_template": "TPL-MOT-ASYNC-070",
    "id_templates": "TPL-MOT-ASYNC-070",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-37",
    "emplacement": "POA-37",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT71-REF-REF75KW2890-POA38-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT71-REF-REF75KW2890-POA38-ZONE-PRESSE-POLYESTER",
    "code": "mot 71",
    "ref": "REF-75KW-2890",
    "libelle": "Moteur Asynchrone 7,5kw 10CV 2890 tr/min",
    "id_template": "TPL-MOT-ASYNC-071",
    "id_templates": "TPL-MOT-ASYNC-071",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-38",
    "emplacement": "POA-38",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT72-REF-REF11KW3000-POA39-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT72-REF-REF11KW3000-POA39-ZONE-PRESSE-POLYESTER",
    "code": "mot 72",
    "ref": "REF-11KW-3000",
    "libelle": "Moteur Asynchrone 11KW 15CV 3000 tr/min",
    "id_template": "TPL-MOT-ASYNC-072",
    "id_templates": "TPL-MOT-ASYNC-072",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-39",
    "emplacement": "POA-39",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT73-REF-REF75KW1430-POA40-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT73-REF-REF75KW1430-POA40-ZONE-PRESSE-POLYESTER",
    "code": "mot 73",
    "ref": "REF-75KW-1430",
    "libelle": "Moteur Asynchrone 7,5KW 10CV 1430 tr/min",
    "id_template": "TPL-MOT-ASYNC-073",
    "id_templates": "TPL-MOT-ASYNC-073",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-40",
    "emplacement": "POA-40",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT74-REF-REF4KW15K1410-PRH01-ZONE-PRESSE-HENICKE",
    "id_entrepot": "ID-MOT74-REF-REF4KW15K1410-PRH01-ZONE-PRESSE-HENICKE",
    "code": "mot 74",
    "ref": "REF-4KW15K-1410",
    "libelle": "Moteur Asynchrone 4KW                         1,5KW                    0,75KW 5,5CV                           2CV                                 1CV 1410                              1420                              1440  tr/min",
    "id_template": "TPL-MOT-ASYNC-074",
    "id_templates": "TPL-MOT-ASYNC-074",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRH-01",
    "emplacement": "PRH-01",
    "zone": "Presse Hénické",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT75-REF-REF22KW111415-PRH02-ZONE-PRESSE-HENICKE",
    "id_entrepot": "ID-MOT75-REF-REF22KW111415-PRH02-ZONE-PRESSE-HENICKE",
    "code": "mot 75",
    "ref": "REF-22KW11-1415",
    "libelle": "Moteur Asynchrone 2,2KW                1,1KW             0,75KW 3CV                               1,5CV                     1CV 1415                             1460                       1440 tr/min",
    "id_template": "TPL-MOT-ASYNC-075",
    "id_templates": "TPL-MOT-ASYNC-075",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRH-02",
    "emplacement": "PRH-02",
    "zone": "Presse Hénické",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT76-REF-REF55KW121440-PRH03-ZONE-PRESSE-HENICKE",
    "id_entrepot": "ID-MOT76-REF-REF55KW121440-PRH03-ZONE-PRESSE-HENICKE",
    "code": "mot 76",
    "ref": "REF-55KW12-1440",
    "libelle": "Moteur Asynchrone 5,5 KW                             1,2KW                    0,75KW 3CV                     1,5CV                            1 CV  1440                             1380                              1390 tr/min",
    "id_template": "TPL-MOT-ASYNC-076",
    "id_templates": "TPL-MOT-ASYNC-076",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRH-03",
    "emplacement": "PRH-03",
    "zone": "Presse Hénické",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT77-REF-REF4KW12K1440-PRH04-ZONE-PRESSE-HENICKE",
    "id_entrepot": "ID-MOT77-REF-REF4KW12K1440-PRH04-ZONE-PRESSE-HENICKE",
    "code": "mot 77",
    "ref": "REF-4KW12K-1440",
    "libelle": "Moteur Asynchrone 4kw                            1,2KW                     0,75KW 5,5 CV                                1,5 CV                         1 CV 1440                                 1380                              1390 tr/min",
    "id_template": "TPL-MOT-ASYNC-077",
    "id_templates": "TPL-MOT-ASYNC-077",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRH-04",
    "emplacement": "PRH-04",
    "zone": "Presse Hénické",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT78-REF-REF4KW12K1440-PRH05-ZONE-PRESSE-HENICKE",
    "id_entrepot": "ID-MOT78-REF-REF4KW12K1440-PRH05-ZONE-PRESSE-HENICKE",
    "code": "mot 78",
    "ref": "REF-4KW12K-1440",
    "libelle": "Moteur Asynchrone 4KW                          1,2KW               0,75KW 5,5CV                                 1,5CV                          1CV 1440                              1380                            1420 tr/min",
    "id_template": "TPL-MOT-ASYNC-078",
    "id_templates": "TPL-MOT-ASYNC-078",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRH-05",
    "emplacement": "PRH-05",
    "zone": "Presse Hénické",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT79-REF-REF4KW15K1500-PRH06-ZONE-PRESSE-HENICKE",
    "id_entrepot": "ID-MOT79-REF-REF4KW15K1500-PRH06-ZONE-PRESSE-HENICKE",
    "code": "mot 79",
    "ref": "REF-4KW15K-1500",
    "libelle": "Moteur Asynchrone 4KW                                 1,5KW 5,5CV                              2CV 1500                               1420 tr/min",
    "id_template": "TPL-MOT-ASYNC-079",
    "id_templates": "TPL-MOT-ASYNC-079",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRH-06",
    "emplacement": "PRH-06",
    "zone": "Presse Hénické",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT80-REF-REFKWNBTO-PRH07-ZONE-PRESSE-HENICKE",
    "id_entrepot": "ID-MOT80-REF-REFKWNBTO-PRH07-ZONE-PRESSE-HENICKE",
    "code": "mot 80",
    "ref": "REF-KW-NBTO",
    "libelle": "Moteur Asynchrone KW CH NB TOURS tr/min",
    "id_template": "TPL-MOT-ASYNC-080",
    "id_templates": "TPL-MOT-ASYNC-080",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRH-07",
    "emplacement": "PRH-07",
    "zone": "Presse Hénické",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT81-REF-REF074KW900-PRM01-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT81-REF-REF074KW900-PRM01-ZONE-PRESSE-MATRICE",
    "code": "mot 81",
    "ref": "REF-074KW-900",
    "libelle": "Moteur Asynchrone 0,74KW 1CV 900 tr/min",
    "id_template": "TPL-MOT-ASYNC-081",
    "id_templates": "TPL-MOT-ASYNC-081",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-01",
    "emplacement": "PRM-01",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT82-REF-REF11KW900-PRM02-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT82-REF-REF11KW900-PRM02-ZONE-PRESSE-MATRICE",
    "code": "mot 82",
    "ref": "REF-11KW-900",
    "libelle": "Moteur Asynchrone 1,1KW 1,5CV 900 tr/min",
    "id_template": "TPL-MOT-ASYNC-082",
    "id_templates": "TPL-MOT-ASYNC-082",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-02",
    "emplacement": "PRM-02",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT83-REF-REF037KW1420-PRM03-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT83-REF-REF037KW1420-PRM03-ZONE-PRESSE-MATRICE",
    "code": "mot 83",
    "ref": "REF-037KW-1420",
    "libelle": "Moteur Asynchrone 0,37KW 0,5CV 1420 tr/min",
    "id_template": "TPL-MOT-ASYNC-083",
    "id_templates": "TPL-MOT-ASYNC-083",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-03",
    "emplacement": "PRM-03",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT84-REF-REF11KW715-PRM04-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT84-REF-REF11KW715-PRM04-ZONE-PRESSE-MATRICE",
    "code": "mot 84",
    "ref": "REF-11KW-715",
    "libelle": "Moteur Asynchrone 1,1KW 1,5CV 715 tr/min",
    "id_template": "TPL-MOT-ASYNC-084",
    "id_templates": "TPL-MOT-ASYNC-084",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-04",
    "emplacement": "PRM-04",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT85-REF-REF075KW920-PRM05-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT85-REF-REF075KW920-PRM05-ZONE-PRESSE-MATRICE",
    "code": "mot 85",
    "ref": "REF-075KW-920",
    "libelle": "Moteur Asynchrone 0,75KW 1CV 920 tr/min",
    "id_template": "TPL-MOT-ASYNC-085",
    "id_templates": "TPL-MOT-ASYNC-085",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-05",
    "emplacement": "PRM-05",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT86-REF-REF15KW900-PRM06-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT86-REF-REF15KW900-PRM06-ZONE-PRESSE-MATRICE",
    "code": "mot 86",
    "ref": "REF-15KW-900",
    "libelle": "Moteur Asynchrone 1,5KW 1,5CV 900 tr/min",
    "id_template": "TPL-MOT-ASYNC-086",
    "id_templates": "TPL-MOT-ASYNC-086",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-06",
    "emplacement": "PRM-06",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT87-REF-REF12KW940-PRM07-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT87-REF-REF12KW940-PRM07-ZONE-PRESSE-MATRICE",
    "code": "mot 87",
    "ref": "REF-12KW-940",
    "libelle": "Moteur Asynchrone 1,2KW 1.6 940 tr/min",
    "id_template": "TPL-MOT-ASYNC-087",
    "id_templates": "TPL-MOT-ASYNC-087",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-07",
    "emplacement": "PRM-07",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT88-REF-REF037KW900-PRM08-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT88-REF-REF037KW900-PRM08-ZONE-PRESSE-MATRICE",
    "code": "mot 88",
    "ref": "REF-037KW-900",
    "libelle": "Moteur Asynchrone 0,37KW 0,5CV 900 tr/min",
    "id_template": "TPL-MOT-ASYNC-088",
    "id_templates": "TPL-MOT-ASYNC-088",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-08",
    "emplacement": "PRM-08",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT89-REF-REF15KW920-PRM09-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT89-REF-REF15KW920-PRM09-ZONE-PRESSE-MATRICE",
    "code": "mot 89",
    "ref": "REF-15KW-920",
    "libelle": "Moteur Asynchrone 1,5KW 2CV 920 tr/min",
    "id_template": "TPL-MOT-ASYNC-089",
    "id_templates": "TPL-MOT-ASYNC-089",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-09",
    "emplacement": "PRM-09",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT90-REF-REF11KW700-PRM10-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT90-REF-REF11KW700-PRM10-ZONE-PRESSE-MATRICE",
    "code": "mot 90",
    "ref": "REF-11KW-700",
    "libelle": "Moteur Asynchrone 1,1KW 1,4CV 700 tr/min",
    "id_template": "TPL-MOT-ASYNC-090",
    "id_templates": "TPL-MOT-ASYNC-090",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-10",
    "emplacement": "PRM-10",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT91-REF-REF11KW720-PRM11-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT91-REF-REF11KW720-PRM11-ZONE-PRESSE-MATRICE",
    "code": "mot 91",
    "ref": "REF-11KW-720",
    "libelle": "Moteur Asynchrone 1,1KW 1,5CV 720 tr/min",
    "id_template": "TPL-MOT-ASYNC-091",
    "id_templates": "TPL-MOT-ASYNC-091",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-11",
    "emplacement": "PRM-11",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT92-REF-REF15KW940-PRM12-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT92-REF-REF15KW940-PRM12-ZONE-PRESSE-MATRICE",
    "code": "mot 92",
    "ref": "REF-15KW-940",
    "libelle": "Moteur Asynchrone 1,5KW 2 940 tr/min",
    "id_template": "TPL-MOT-ASYNC-092",
    "id_templates": "TPL-MOT-ASYNC-092",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-12",
    "emplacement": "PRM-12",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT93-REF-REF11KW2980-PRM13-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT93-REF-REF11KW2980-PRM13-ZONE-PRESSE-MATRICE",
    "code": "mot 93",
    "ref": "REF-11KW-2980",
    "libelle": "Moteur Asynchrone 1,1KW 1,5 CV 2980 tr/min",
    "id_template": "TPL-MOT-ASYNC-093",
    "id_templates": "TPL-MOT-ASYNC-093",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-13",
    "emplacement": "PRM-13",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT94-REF-REF3KW2950-PRM14-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT94-REF-REF3KW2950-PRM14-ZONE-PRESSE-MATRICE",
    "code": "mot 94",
    "ref": "REF-3KW-2950",
    "libelle": "Moteur Asynchrone 3KW 4 CV 2950 tr/min",
    "id_template": "TPL-MOT-ASYNC-094",
    "id_templates": "TPL-MOT-ASYNC-094",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-14",
    "emplacement": "PRM-14",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT95-REF-REF18KW2920-PRM15-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT95-REF-REF18KW2920-PRM15-ZONE-PRESSE-MATRICE",
    "code": "mot 95",
    "ref": "REF-18KW-2920",
    "libelle": "Moteur Asynchrone 1,8KW 2,5 CV 2920 tr/min",
    "id_template": "TPL-MOT-ASYNC-095",
    "id_templates": "TPL-MOT-ASYNC-095",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-15",
    "emplacement": "PRM-15",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT96-REF-REF15KW2950-PRM16-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT96-REF-REF15KW2950-PRM16-ZONE-PRESSE-MATRICE",
    "code": "mot 96",
    "ref": "REF-15KW-2950",
    "libelle": "Moteur Asynchrone 1,5KW 2 CV 2950 tr/min",
    "id_template": "TPL-MOT-ASYNC-096",
    "id_templates": "TPL-MOT-ASYNC-096",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-16",
    "emplacement": "PRM-16",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT97-REF-REF11KW2950-PRM17-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT97-REF-REF11KW2950-PRM17-ZONE-PRESSE-MATRICE",
    "code": "mot 97",
    "ref": "REF-11KW-2950",
    "libelle": "Moteur Asynchrone 1,1KW 1,5 CV 2950 tr/min",
    "id_template": "TPL-MOT-ASYNC-097",
    "id_templates": "TPL-MOT-ASYNC-097",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-17",
    "emplacement": "PRM-17",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT98-REF-REF075KW3000-PRM18-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT98-REF-REF075KW3000-PRM18-ZONE-PRESSE-MATRICE",
    "code": "mot 98",
    "ref": "REF-075KW-3000",
    "libelle": "Moteur Asynchrone 0,75KW 1 CV 3000 tr/min",
    "id_template": "TPL-MOT-ASYNC-098",
    "id_templates": "TPL-MOT-ASYNC-098",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-18",
    "emplacement": "PRM-18",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT99-REF-REF075KW2950-PRM19-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT99-REF-REF075KW2950-PRM19-ZONE-PRESSE-MATRICE",
    "code": "mot 99",
    "ref": "REF-075KW-2950",
    "libelle": "Moteur Asynchrone 0,75KW 1 CV 2950 tr/min",
    "id_template": "TPL-MOT-ASYNC-099",
    "id_templates": "TPL-MOT-ASYNC-099",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-19",
    "emplacement": "PRM-19",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT100-REF-REF075KW2980-PRM20-ZONE-PRESSE-MATRICE",
    "id_entrepot": "ID-MOT100-REF-REF075KW2980-PRM20-ZONE-PRESSE-MATRICE",
    "code": "mot 100",
    "ref": "REF-075KW-2980",
    "libelle": "Moteur Asynchrone 0,75KW 1 CV 2980 tr/min",
    "id_template": "TPL-MOT-ASYNC-100",
    "id_templates": "TPL-MOT-ASYNC-100",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PRM-20",
    "emplacement": "PRM-20",
    "zone": "Presse Matrice",
    "etat": "Actif",
    "historique_bobinage": []
  }
]
