# scripts/data_motors_part1.py
MOTORS_PART1 = [
  {
    "id": "ID-MOT01-REF-REF10A111NA-DET01-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT01-REF-REF10A111NA-DET01-ZONE-DETOURAGE",
    "code": "mot 01",
    "ref": "REF-10A111-NA",
    "libelle": "Moteur Asynchrone 10A-11,1A/1,1A   tr/min",
    "id_template": "TPL-MOT-ASYNC-001",
    "id_templates": "TPL-MOT-ASYNC-001",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-01",
    "emplacement": "DET-01",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT02-REF-REF40KWNA-DET02-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT02-REF-REF40KWNA-DET02-ZONE-DETOURAGE",
    "code": "mot 02",
    "ref": "REF-40KW-NA",
    "libelle": "Moteur Asynchrone 4,0KW   tr/min",
    "id_template": "TPL-MOT-ASYNC-002",
    "id_templates": "TPL-MOT-ASYNC-002",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-02",
    "emplacement": "DET-02",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT03-REF-REF75KW05NA-DET03-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT03-REF-REF75KW05NA-DET03-ZONE-DETOURAGE",
    "code": "mot 03",
    "ref": "REF-75KW05-NA",
    "libelle": "Moteur Asynchrone 7,5 KW/0,55KW   tr/min",
    "id_template": "TPL-MOT-ASYNC-003",
    "id_templates": "TPL-MOT-ASYNC-003",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-03",
    "emplacement": "DET-03",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT04-REF-REF3ANA-DET04-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT04-REF-REF3ANA-DET04-ZONE-DETOURAGE",
    "code": "mot 04",
    "ref": "REF-3A-NA",
    "libelle": "Moteur Asynchrone 3A   tr/min",
    "id_template": "TPL-MOT-ASYNC-004",
    "id_templates": "TPL-MOT-ASYNC-004",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-04",
    "emplacement": "DET-04",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT05-REF-REF22KWNA-DET05-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT05-REF-REF22KWNA-DET05-ZONE-DETOURAGE",
    "code": "mot 05",
    "ref": "REF-22KW-NA",
    "libelle": "Moteur Asynchrone 2,2KW   tr/min",
    "id_template": "TPL-MOT-ASYNC-005",
    "id_templates": "TPL-MOT-ASYNC-005",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-05",
    "emplacement": "DET-05",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT06-REF-REF55KWNA-DET06-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT06-REF-REF55KWNA-DET06-ZONE-DETOURAGE",
    "code": "mot 06",
    "ref": "REF-55KW-NA",
    "libelle": "Moteur Asynchrone 5,5KW   tr/min",
    "id_template": "TPL-MOT-ASYNC-006",
    "id_templates": "TPL-MOT-ASYNC-006",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-06",
    "emplacement": "DET-06",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT07-REF-REF27ANA-DET07-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT07-REF-REF27ANA-DET07-ZONE-DETOURAGE",
    "code": "mot 07",
    "ref": "REF-27A-NA",
    "libelle": "Moteur Asynchrone 2,7A   tr/min",
    "id_template": "TPL-MOT-ASYNC-007",
    "id_templates": "TPL-MOT-ASYNC-007",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-07",
    "emplacement": "DET-07",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT08-REF-REF716ANA-DET08-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT08-REF-REF716ANA-DET08-ZONE-DETOURAGE",
    "code": "mot 08",
    "ref": "REF-716A-NA",
    "libelle": "Moteur Asynchrone 7,16A   tr/min",
    "id_template": "TPL-MOT-ASYNC-008",
    "id_templates": "TPL-MOT-ASYNC-008",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-08",
    "emplacement": "DET-08",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT09-REF-REF45KWNA-DET09-ZONE-DETOURAGE",
    "id_entrepot": "ID-MOT09-REF-REF45KWNA-DET09-ZONE-DETOURAGE",
    "code": "mot 09",
    "ref": "REF-45KW-NA",
    "libelle": "Moteur Asynchrone 4,5KW   tr/min",
    "id_template": "TPL-MOT-ASYNC-009",
    "id_templates": "TPL-MOT-ASYNC-009",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "DET-09",
    "emplacement": "DET-09",
    "zone": "Détourage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT10-REF-REF15KW1400-PCE01-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "id_entrepot": "ID-MOT10-REF-REF15KW1400-PCE01-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "code": "mot 10",
    "ref": "REF-15KW-1400",
    "libelle": "Moteur Asynchrone 1,5KW 2CV 1400 tr/min",
    "id_template": "TPL-MOT-ASYNC-010",
    "id_templates": "TPL-MOT-ASYNC-010",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PCE-01",
    "emplacement": "PCE-01",
    "zone": "Préparation Corniche et Emballage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT11-REF-REF75KW920-FRL01-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT11-REF-REF75KW920-FRL01-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 11",
    "ref": "REF-75KW-920",
    "libelle": "Moteur Asynchrone 7,5KW 10CV 920 tr/min",
    "id_template": "TPL-MOT-ASYNC-011",
    "id_templates": "TPL-MOT-ASYNC-011",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-01",
    "emplacement": "FRL-01",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT12-REF-REF9KW1430-FRL02-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT12-REF-REF9KW1430-FRL02-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 12",
    "ref": "REF-9KW-1430",
    "libelle": "Moteur Asynchrone 9KW 12,5CV 1430 tr/min",
    "id_template": "TPL-MOT-ASYNC-012",
    "id_templates": "TPL-MOT-ASYNC-012",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-02",
    "emplacement": "FRL-02",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT13-REF-REF22KW1500-FRL03-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT13-REF-REF22KW1500-FRL03-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 13",
    "ref": "REF-22KW-1500",
    "libelle": "Moteur Asynchrone 2,2KW 3CV 1500 tr/min",
    "id_template": "TPL-MOT-ASYNC-013",
    "id_templates": "TPL-MOT-ASYNC-013",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-03",
    "emplacement": "FRL-03",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT14-REF-REF075KW1410-FRL04-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT14-REF-REF075KW1410-FRL04-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 14",
    "ref": "REF-075KW-1410",
    "libelle": "Moteur Asynchrone 0,75KW 1CV 1410 tr/min",
    "id_template": "TPL-MOT-ASYNC-014",
    "id_templates": "TPL-MOT-ASYNC-014",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-04",
    "emplacement": "FRL-04",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT15-REF-REF075KW1350-FRL05-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT15-REF-REF075KW1350-FRL05-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 15",
    "ref": "REF-075KW-1350",
    "libelle": "Moteur Asynchrone 0,75KW 1CV 1350 tr/min",
    "id_template": "TPL-MOT-ASYNC-015",
    "id_templates": "TPL-MOT-ASYNC-015",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-05",
    "emplacement": "FRL-05",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT16-REF-REF3KW1400-FRL06-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT16-REF-REF3KW1400-FRL06-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 16",
    "ref": "REF-3KW-1400",
    "libelle": "Moteur Asynchrone 3KW 4CV 1400 tr/min",
    "id_template": "TPL-MOT-ASYNC-016",
    "id_templates": "TPL-MOT-ASYNC-016",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-06",
    "emplacement": "FRL-06",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT17-REF-REF3KW1430-FRL07-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT17-REF-REF3KW1430-FRL07-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 17",
    "ref": "REF-3KW-1430",
    "libelle": "Moteur Asynchrone 3KW 4CV 1430 tr/min",
    "id_template": "TPL-MOT-ASYNC-017",
    "id_templates": "TPL-MOT-ASYNC-017",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-07",
    "emplacement": "FRL-07",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT18-REF-REF11KW1460-FRL08-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT18-REF-REF11KW1460-FRL08-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 18",
    "ref": "REF-11KW-1460",
    "libelle": "Moteur Asynchrone 11KW 15CV 1460 tr/min",
    "id_template": "TPL-MOT-ASYNC-018",
    "id_templates": "TPL-MOT-ASYNC-018",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-08",
    "emplacement": "FRL-08",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT19-REF-REF4KW1425-FRL09-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT19-REF-REF4KW1425-FRL09-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 19",
    "ref": "REF-4KW-1425",
    "libelle": "Moteur Asynchrone 4 KW 5,5CV 1425 tr/min",
    "id_template": "TPL-MOT-ASYNC-019",
    "id_templates": "TPL-MOT-ASYNC-019",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-09",
    "emplacement": "FRL-09",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT20-REF-REF21KW880-FRL10-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT20-REF-REF21KW880-FRL10-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 20",
    "ref": "REF-21KW-880",
    "libelle": "Moteur Asynchrone 2,1 KW 2,8CV 880 tr/min",
    "id_template": "TPL-MOT-ASYNC-020",
    "id_templates": "TPL-MOT-ASYNC-020",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-10",
    "emplacement": "FRL-10",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT21-REF-REF11KW1460-FRL11-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT21-REF-REF11KW1460-FRL11-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 21",
    "ref": "REF-11KW-1460",
    "libelle": "Moteur Asynchrone 11 KW 14CV 1460 tr/min",
    "id_template": "TPL-MOT-ASYNC-021",
    "id_templates": "TPL-MOT-ASYNC-021",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-11",
    "emplacement": "FRL-11",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT22-REF-REF75KW1435-FRL12-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT22-REF-REF75KW1435-FRL12-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 22",
    "ref": "REF-75KW-1435",
    "libelle": "Moteur Asynchrone 7,5 KW 10CV 1435 tr/min",
    "id_template": "TPL-MOT-ASYNC-022",
    "id_templates": "TPL-MOT-ASYNC-022",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-12",
    "emplacement": "FRL-12",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT23-REF-REF22KW1460-FRL13-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT23-REF-REF22KW1460-FRL13-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 23",
    "ref": "REF-22KW-1460",
    "libelle": "Moteur Asynchrone 2,2KW 3CV 1460 tr/min",
    "id_template": "TPL-MOT-ASYNC-023",
    "id_templates": "TPL-MOT-ASYNC-023",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-13",
    "emplacement": "FRL-13",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT24-REF-REF75KW1460-FRL14-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT24-REF-REF75KW1460-FRL14-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 24",
    "ref": "REF-75KW-1460",
    "libelle": "Moteur Asynchrone 7,5KW 10CV 1460 tr/min",
    "id_template": "TPL-MOT-ASYNC-024",
    "id_templates": "TPL-MOT-ASYNC-024",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-14",
    "emplacement": "FRL-14",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT25-REF-REF75KW2910-FRL15-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT25-REF-REF75KW2910-FRL15-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 25",
    "ref": "REF-75KW-2910",
    "libelle": "Moteur Asynchrone 7,5 KW 10CV 2910 tr/min",
    "id_template": "TPL-MOT-ASYNC-025",
    "id_templates": "TPL-MOT-ASYNC-025",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-15",
    "emplacement": "FRL-15",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT26-REF-REF44KW1430-FRL16-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT26-REF-REF44KW1430-FRL16-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 26",
    "ref": "REF-44KW-1430",
    "libelle": "Moteur Asynchrone 4,4KW 6CV 1430 tr/min",
    "id_template": "TPL-MOT-ASYNC-026",
    "id_templates": "TPL-MOT-ASYNC-026",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-16",
    "emplacement": "FRL-16",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT27-REF-REF11KW960-FRL17-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT27-REF-REF11KW960-FRL17-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 27",
    "ref": "REF-11KW-960",
    "libelle": "Moteur Asynchrone 11KW 15CV 960 tr/min",
    "id_template": "TPL-MOT-ASYNC-027",
    "id_templates": "TPL-MOT-ASYNC-027",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-17",
    "emplacement": "FRL-17",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT28-REF-REF147KW1337-FRL18-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT28-REF-REF147KW1337-FRL18-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 28",
    "ref": "REF-147KW-1337",
    "libelle": "Moteur Asynchrone 14,7kw 20CV 1337 tr/min",
    "id_template": "TPL-MOT-ASYNC-028",
    "id_templates": "TPL-MOT-ASYNC-028",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-18",
    "emplacement": "FRL-18",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT29-REF-REF22KW1430-FRL19-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT29-REF-REF22KW1430-FRL19-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 29",
    "ref": "REF-22KW-1430",
    "libelle": "Moteur Asynchrone 2,2KW 3 CV 1430 tr/min",
    "id_template": "TPL-MOT-ASYNC-029",
    "id_templates": "TPL-MOT-ASYNC-029",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-19",
    "emplacement": "FRL-19",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT30-REF-REF92KW1410-FRL20-ZONE-FRAISAGE-ET-LIGNES",
    "id_entrepot": "ID-MOT30-REF-REF92KW1410-FRL20-ZONE-FRAISAGE-ET-LIGNES",
    "code": "mot 30",
    "ref": "REF-92KW-1410",
    "libelle": "Moteur Asynchrone 9,2KW 12,5 CV 1410 tr/min",
    "id_template": "TPL-MOT-ASYNC-030",
    "id_templates": "TPL-MOT-ASYNC-030",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "FRL-20",
    "emplacement": "FRL-20",
    "zone": "Fraisage et Lignes",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT31-REF-REF0753000-PCE02-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "id_entrepot": "ID-MOT31-REF-REF0753000-PCE02-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "code": "mot 31",
    "ref": "REF-075-3000",
    "libelle": "Moteur Asynchrone 0.75 1CV 3000 tr/min",
    "id_template": "TPL-MOT-ASYNC-031",
    "id_templates": "TPL-MOT-ASYNC-031",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PCE-02",
    "emplacement": "PCE-02",
    "zone": "Préparation Corniche et Emballage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT32-REF-REF22KW1425-PCE03-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "id_entrepot": "ID-MOT32-REF-REF22KW1425-PCE03-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "code": "mot 32",
    "ref": "REF-22KW-1425",
    "libelle": "Moteur Asynchrone 2,2KW 3CV 1425 tr/min",
    "id_template": "TPL-MOT-ASYNC-032",
    "id_templates": "TPL-MOT-ASYNC-032",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PCE-03",
    "emplacement": "PCE-03",
    "zone": "Préparation Corniche et Emballage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT33-REF-REF15KW2870-PCE04-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "id_entrepot": "ID-MOT33-REF-REF15KW2870-PCE04-ZONE-PREPARATION-CORNICHE-ET-EMBALLAGE",
    "code": "mot 33",
    "ref": "REF-15KW-2870",
    "libelle": "Moteur Asynchrone 1,5KW 2CV 2870 tr/min",
    "id_template": "TPL-MOT-ASYNC-033",
    "id_templates": "TPL-MOT-ASYNC-033",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "PCE-04",
    "emplacement": "PCE-04",
    "zone": "Préparation Corniche et Emballage",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT34-REF-REF56KWNA-POA01-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT34-REF-REF56KWNA-POA01-ZONE-PRESSE-POLYESTER",
    "code": "mot 34",
    "ref": "REF-56KW-NA",
    "libelle": "Moteur Asynchrone 5,6KW * * tr/min",
    "id_template": "TPL-MOT-ASYNC-034",
    "id_templates": "TPL-MOT-ASYNC-034",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-01",
    "emplacement": "POA-01",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT35-REF-REF45KW551475-POA02-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT35-REF-REF45KW551475-POA02-ZONE-PRESSE-POLYESTER",
    "code": "mot 35",
    "ref": "REF-45KW55-1475",
    "libelle": "Moteur Asynchrone 45kw 5,5kw 60CV 7,5CV 1475 1470 tr/min",
    "id_template": "TPL-MOT-ASYNC-035",
    "id_templates": "TPL-MOT-ASYNC-035",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-02",
    "emplacement": "POA-02",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT36-REF-REF185KW11460-POA03-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT36-REF-REF185KW11460-POA03-ZONE-PRESSE-POLYESTER",
    "code": "mot 36",
    "ref": "REF-185KW1-1460",
    "libelle": "Moteur Asynchrone 18,5KW 1,5KW 25CV 2 CV 1460 1420 tr/min",
    "id_template": "TPL-MOT-ASYNC-036",
    "id_templates": "TPL-MOT-ASYNC-036",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-03",
    "emplacement": "POA-03",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT37-REF-REF30KW151465-POA04-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT37-REF-REF30KW151465-POA04-ZONE-PRESSE-POLYESTER",
    "code": "mot 37",
    "ref": "REF-30KW15-1465",
    "libelle": "Moteur Asynchrone 30KW 1,5KW 40 CV 2 CV 1465 1460 tr/min",
    "id_template": "TPL-MOT-ASYNC-037",
    "id_templates": "TPL-MOT-ASYNC-037",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-04",
    "emplacement": "POA-04",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT38-REF-REF37KW141475-POA05-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT38-REF-REF37KW141475-POA05-ZONE-PRESSE-POLYESTER",
    "code": "mot 38",
    "ref": "REF-37KW14-1475",
    "libelle": "Moteur Asynchrone 37KW 1,45KW 50 CV 2 CV 1475 1450 tr/min",
    "id_template": "TPL-MOT-ASYNC-038",
    "id_templates": "TPL-MOT-ASYNC-038",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-05",
    "emplacement": "POA-05",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT39-REF-REF45KW4K1400-POA06-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT39-REF-REF45KW4K1400-POA06-ZONE-PRESSE-POLYESTER",
    "code": "mot 39",
    "ref": "REF-45KW4K-1400",
    "libelle": "Moteur Asynchrone 45kw 4 kw 60CV 5,5CV 1400 1750 tr/min",
    "id_template": "TPL-MOT-ASYNC-039",
    "id_templates": "TPL-MOT-ASYNC-039",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-06",
    "emplacement": "POA-06",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT40-REF-REF13KW1400-POA07-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT40-REF-REF13KW1400-POA07-ZONE-PRESSE-POLYESTER",
    "code": "mot 40",
    "ref": "REF-13KW-1400",
    "libelle": "Moteur Asynchrone 13 KW 18 CV 1400 tr/min",
    "id_template": "TPL-MOT-ASYNC-040",
    "id_templates": "TPL-MOT-ASYNC-040",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-07",
    "emplacement": "POA-07",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT41-REF-REF13KW1440-POA08-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT41-REF-REF13KW1440-POA08-ZONE-PRESSE-POLYESTER",
    "code": "mot 41",
    "ref": "REF-13KW-1440",
    "libelle": "Moteur Asynchrone 13 KW 18 CV 1440 tr/min",
    "id_template": "TPL-MOT-ASYNC-041",
    "id_templates": "TPL-MOT-ASYNC-041",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-08",
    "emplacement": "POA-08",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": [
      {
        "date_demontage": "24/06/2021",
        "technicien_demontage": "Soufiane",
        "cause": "grille",
        "observation": "moteur bruillant",
        "date_reception": "29/06/2021",
        "statut_bobinage": "Rebobiné",
        "societe_bobinage": "STE AMAL"
      }
    ]
  },
  {
    "id": "ID-MOT42-REF-REF15KW151456-POA09-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT42-REF-REF15KW151456-POA09-ZONE-PRESSE-POLYESTER",
    "code": "mot 42",
    "ref": "REF-15KW15-1456",
    "libelle": "Moteur Asynchrone 15kw 1,5kw 20CV 2CV 1456 1420 tr/min",
    "id_template": "TPL-MOT-ASYNC-042",
    "id_templates": "TPL-MOT-ASYNC-042",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-09",
    "emplacement": "POA-09",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT43-REF-REF37KW751475-POA10-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT43-REF-REF37KW751475-POA10-ZONE-PRESSE-POLYESTER",
    "code": "mot 43",
    "ref": "REF-37KW75-1475",
    "libelle": "Moteur Asynchrone 37KW 7,5KW 50 CV 10CV 1475 1445 tr/min",
    "id_template": "TPL-MOT-ASYNC-043",
    "id_templates": "TPL-MOT-ASYNC-043",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-10",
    "emplacement": "POA-10",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT44-REF-REF15KW151455-POA11-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT44-REF-REF15KW151455-POA11-ZONE-PRESSE-POLYESTER",
    "code": "mot 44",
    "ref": "REF-15KW15-1455",
    "libelle": "Moteur Asynchrone 15KW 1,5KW 20CV 2CV 1455 1420 tr/min",
    "id_template": "TPL-MOT-ASYNC-044",
    "id_templates": "TPL-MOT-ASYNC-044",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-11",
    "emplacement": "POA-11",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT45-REF-REF11KW151445-POA12-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT45-REF-REF11KW151445-POA12-ZONE-PRESSE-POLYESTER",
    "code": "mot 45",
    "ref": "REF-11KW15-1445",
    "libelle": "Moteur Asynchrone 11KW 1,5KW 15CV 2CV 1445 tr/min",
    "id_template": "TPL-MOT-ASYNC-045",
    "id_templates": "TPL-MOT-ASYNC-045",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-12",
    "emplacement": "POA-12",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT46-REF-REF125KW1430-POA13-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT46-REF-REF125KW1430-POA13-ZONE-PRESSE-POLYESTER",
    "code": "mot 46",
    "ref": "REF-125KW-1430",
    "libelle": "Moteur Asynchrone 12,5KW 17CV 1430 tr/min",
    "id_template": "TPL-MOT-ASYNC-046",
    "id_templates": "TPL-MOT-ASYNC-046",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-13",
    "emplacement": "POA-13",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT47-REF-REF30KW1465-POA14-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT47-REF-REF30KW1465-POA14-ZONE-PRESSE-POLYESTER",
    "code": "mot 47",
    "ref": "REF-30KW-1465",
    "libelle": "Moteur Asynchrone 30KW 40 CV 1465 tr/min",
    "id_template": "TPL-MOT-ASYNC-047",
    "id_templates": "TPL-MOT-ASYNC-047",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-14",
    "emplacement": "POA-14",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT48-REF-REF22KW1455-POA15-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT48-REF-REF22KW1455-POA15-ZONE-PRESSE-POLYESTER",
    "code": "mot 48",
    "ref": "REF-22KW-1455",
    "libelle": "Moteur Asynchrone 22KW 30 CV 1455 tr/min",
    "id_template": "TPL-MOT-ASYNC-048",
    "id_templates": "TPL-MOT-ASYNC-048",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-15",
    "emplacement": "POA-15",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT49-REF-REF30KW2960-POA16-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT49-REF-REF30KW2960-POA16-ZONE-PRESSE-POLYESTER",
    "code": "mot 49",
    "ref": "REF-30KW-2960",
    "libelle": "Moteur Asynchrone 30 KW 40 CV 2960 tr/min",
    "id_template": "TPL-MOT-ASYNC-049",
    "id_templates": "TPL-MOT-ASYNC-049",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-16",
    "emplacement": "POA-16",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  },
  {
    "id": "ID-MOT50-REF-REF55KW3000-POA17-ZONE-PRESSE-POLYESTER",
    "id_entrepot": "ID-MOT50-REF-REF55KW3000-POA17-ZONE-PRESSE-POLYESTER",
    "code": "mot 50",
    "ref": "REF-55KW-3000",
    "libelle": "Moteur Asynchrone 55 KW 74,32CV 3000 tr/min",
    "id_template": "TPL-MOT-ASYNC-050",
    "id_templates": "TPL-MOT-ASYNC-050",
    "id_family": "FAM-MOTEUR-ELEC-001",
    "id_machine": "POA-17",
    "emplacement": "POA-17",
    "zone": "Presse Polyester",
    "etat": "Actif",
    "historique_bobinage": []
  }
]
